# LLM API
OPENAI_ENDPOINT = "https://api.openai.com/v1" # https://api.deepseek.com/v1 for DeepSeek
OPENAI_API_KEY = "sk-xxxxx"
MODEL = "gpt-4o-mini" # deepseek-chat for DeepSeek

# 讯飞 API
XUNFEI_APP_ID = "bf3xxxxx"
XUNFEI_SECRET_KEY = "feb927exxxxxxxxxxxxxxxxxxx"

# 课程名称
COURSE_NAME = "OS"

# 笔记风格
STYLE = "note" # "note" 会生成笔记，"cleaner" 会生成讲稿
